
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar mainMenuBar;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.ComboBox psalmNumberSelector;
	private global::Gtk.Button psalmSelectButton;
	private global::Gtk.VBox vbox3;
	private global::Gtk.ComboBox psalmVersionSelector;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView psalmViewingSpace;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, "<Mod2>space");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Tehillim");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mainMenuBar'><menu name='FileAction' action='FileAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.mainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mainMenuBar")));
		this.mainMenuBar.Name = "mainMenuBar";
		this.vbox1.Add (this.mainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 160;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 35;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.psalmNumberSelector = global::Gtk.ComboBox.NewText ();
		this.psalmNumberSelector.Name = "psalmNumberSelector";
		this.vpaned1.Add (this.psalmNumberSelector);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.psalmNumberSelector]));
		w3.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.psalmSelectButton = new global::Gtk.Button ();
		this.psalmSelectButton.CanFocus = true;
		this.psalmSelectButton.Name = "psalmSelectButton";
		this.psalmSelectButton.UseUnderline = true;
		this.psalmSelectButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vpaned1.Add (this.psalmSelectButton);
		this.hpaned1.Add (this.vpaned1);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned1]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.psalmVersionSelector = global::Gtk.ComboBox.NewText ();
		this.psalmVersionSelector.Name = "psalmVersionSelector";
		this.vbox3.Add (this.psalmVersionSelector);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.psalmVersionSelector]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.psalmViewingSpace = new global::Gtk.TextView ();
		this.psalmViewingSpace.CanFocus = true;
		this.psalmViewingSpace.Name = "psalmViewingSpace";
		this.psalmViewingSpace.Editable = false;
		this.GtkScrolledWindow.Add (this.psalmViewingSpace);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w8.Position = 1;
		this.hpaned1.Add (this.vbox3);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w10.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 718;
		this.DefaultHeight = 556;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AboutAction.Activated += new global::System.EventHandler (this.about);
		this.psalmSelectButton.Clicked += new global::System.EventHandler (this.psalmSelected);
	}
}
